#pragma once

#define FIFSCREEN_VERSION_MAJOR 0
#define FIFSCREEN_VERSION_MINOR 5
#define FIFSCREEN_VERSION_PATCH 3
#define FIFSCREEN_VERSION_BUILD 0
#define FIFSCREEN_VERSION_COMMA 0,5,3,0
#define FIFSCREEN_VERSION_STRING "0.5.3"
