#pragma once

#define FIFSCREEN_VERSION_MAJOR 0
#define FIFSCREEN_VERSION_MINOR 3
#define FIFSCREEN_VERSION_PATCH 1
#define FIFSCREEN_VERSION_BUILD 0
#define FIFSCREEN_VERSION_COMMA 0,3,1,0
#define FIFSCREEN_VERSION_STRING "0.3.1"
